In [3]:
import numpy as np

arr1=np.array([1,2,3,4,5,6,7,8])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
(8,)


In [4]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(type(arr2))
print(arr2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)


In [9]:
arr3=np.arange(1,10).reshape(9,1)
print(arr3)
print(type(arr3))
print(arr3.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
<class 'numpy.ndarray'>
(9, 1)


In [11]:
arr4=np.ones((3,4))
print(arr4)
print(type(arr4))
print(arr4.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>
(3, 4)


In [12]:
arr4=np.zeros((3,4))
print(arr4)
print(type(arr4))
print(arr4.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<class 'numpy.ndarray'>
(3, 4)


In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(f'array: {arr}')
print(f'shape: {arr.shape}')
print(f'dimensions: {arr.ndim}')
print(f'size: {arr.size}')
print(f'data_type: {arr.dtype}')
print(f'Item size: {arr.itemsize}')

array: [1 2 3 4 5 6 7 8 9]
shape: (9,)
dimensions: 1
size: 9
data_type: int64
Item size: 8


In [15]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
arr2=np.array([1,2,3,4,5,6,7,8,9])

print(f'addition: {arr1+arr2}')
print(f'Subtraction: {arr1-arr2}')
print(f'Multiplication: {arr1*arr2}')
print(f'Division: {arr1/arr2}')


addition: [ 2  4  6  8 10 12 14 16 18]
Subtraction: [0 0 0 0 0 0 0 0 0]
Multiplication: [ 1  4  9 16 25 36 49 64 81]
Division: [1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [17]:
print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.sin(arr1))
print(np.log(arr1))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr[0][1])
print(arr[1:,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[[ 7  8]
 [11 12]]
